# Generated by Django 4.1.7 on 2023-12-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_userpayment_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='subscription_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_subscription_id',
            field=models.CharField(default='No value', max_length=500),
            preserve_default=False,
        ),
    ]
