# Generated by Django 4.1.7 on 2023-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_subscription_id_userpayment_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='stripe_usage_billing_id',
            field=models.CharField(default='no id', max_length=500),
            preserve_default=False,
        ),
    ]
