# Generated by Django 4.1.7 on 2023-12-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_userpayment_stripe_usage_billing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_usage_billing_id',
            field=models.CharField(max_length=500),
        ),
    ]
