# Generated by Django 4.1.7 on 2023-12-24 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Cases',
        ),
    ]
