# Generated by Django 4.1.7 on 2023-12-24 05:45

import cases.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_cases_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file_upload',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_upload', models.FileField(upload_to=cases.models.file_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cases.case')),
            ],
        ),
    ]
