# Generated by Django 4.1.7 on 2023-12-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_file_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='test.pdf', max_length=255),
            preserve_default=False,
        ),
    ]
