# Generated by Django 4.1.7 on 2023-12-31 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('user', 'is_active')},
        ),
    ]
