# Generated by Django 4.1.7 on 2023-12-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_is_active_alter_case_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set(),
        ),
    ]
